### ISSUE TITLE
Sprockets::ArgumentError: link_directory argument must be a directory

### ISSUE THREAD

**Issue by ioio000** [ranguba/chupa-text-docker#5]
The docker image does not work with the latest version.
I tried the following:

```
git clone https://github.com/ranguba/chupa-text-docker.git
cd chupa-text-docker
docker compose up
...
 => [groonga/chupa-text:ubuntu-latest 14/16] WORKDIR /home/chupa-text/chupa-text-http-server                       0.0s
 => [groonga/chupa-text:ubuntu-latest 15/16] RUN   sudo apt update &&   bundle config set --local without "dev  1079.9s
 => ERROR [groonga/chupa-text:ubuntu-latest 16/16] RUN   bin/rails assets:precompile                              26.5s
------
 > [groonga/chupa-text:ubuntu-latest 16/16] RUN   bin/rails assets:precompile:
#26 3.593 yarn install v1.22.5
#26 3.685 [1/4] Resolving packages...
#26 4.067 [2/4] Fetching packages...
#26 18.06 info fsevents@2.3.2: The platform "linux" is incompatible with this module.
#26 18.06 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
#26 18.06 info fsevents@1.2.13: The platform "linux" is incompatible with this module.
#26 18.06 info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
#26 18.06 [3/4] Linking dependencies...
#26 18.07 warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
#26 18.07 warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
#26 23.81 [4/4] Building fresh packages...
#26 26.02 Done in 22.43s.
#26 26.04 rails aborted!
#26 26.04 Sprockets::ArgumentError: link_directory argument must be a directory
#26 26.04 /home/chupa-text/chupa-text-http-server/app/assets/config/manifest.js:2
#26 26.04 Tasks: TOP => assets:precompile
#26 26.04 (See full trace by running task with --trace)
------
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c bin/rails assets:precompile]: exit code: 1

```

I created the directories "javascripts" and "stylesheets" described in manifest.js.
Added to Dockerfile :
_RUN \
  mkdir app/assets/javascripts && \
  mkdir app/assets/stylesheets_

[log.zip](https://github.com/ranguba/chupa-text-docker/files/6292160/log.zip)

```
docker compose up
...
 => [groonga/chupa-text:ubuntu-latest 14/17] WORKDIR /home/chupa-text/chupa-text-http-server                       0.0s
 => [groonga/chupa-text:ubuntu-latest 15/17] RUN   mkdir app/assets/javascripts &&   mkdir app/assets/stylesheets  0.4s
 => [groonga/chupa-text:ubuntu-latest 16/17] RUN   sudo apt update &&   bundle config set --local without "deve  800.4s
 => [groonga/chupa-text:ubuntu-latest 17/17] RUN   bin/rails assets:precompile                                    40.6s
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 2/2
 - Container chupa-text-docker_proxy_1       Created                       0.1s
 - Container chupa-text-docker_chupa-text_1  Created                       0.1s
Attaching to chupa-text-docker_chupa-text_1, chupa-text-docker_proxy_1
proxy_1       | 2021/04/11 14:53:31| WARNING: BCP 177 violation. Detected non-functional IPv6 loopback.
chupa-text_1  |  --> Downloading a Phusion Passenger(R) agent binary for your platform
chupa-text_1  |
chupa-text_1  |  --> Installing Nginx 1.18.0 engine
chupa-text_1  |
chupa-text_1  | --------------------------
chupa-text_1  |
chupa-text_1  |  [passenger_native_support.so] trying to compile for the current user (chupa-text) and Ruby interpreter...
chupa-text_1  |      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
chupa-text_1  |      Compilation successful. The logs are here:
chupa-text_1  |      /tmp/passenger_native_support-vpkmax.log
chupa-text_1  |  [passenger_native_support.so] successfully loaded.
chupa-text_1  | =============== Phusion Passenger(R) Standalone web server started ===============
chupa-text_1  | PID file: /home/chupa-text/chupa-text-http-server/passenger.3000.pid
chupa-text_1  | Log file: /home/chupa-text/chupa-text-http-server/log/passenger.3000.log
chupa-text_1  | Environment: production
chupa-text_1  | Accessible via: http://0.0.0.0:3000/
chupa-text_1  |
chupa-text_1  | You can stop Phusion Passenger(R) Standalone by pressing Ctrl-C.
chupa-text_1  | Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
chupa-text_1  | ===============================================================================
chupa-text_1  | App 180 output: Error: The application encountered the following error: uninitialized constant ApplicationCable::ActionCable
chupa-text_1  | App 180 output: Did you mean?  Rational (NameError)
chupa-text_1  | App 180 output:     /home/chupa-text/chupa-text-http-server/app/channels/application_cable/channel.rb:2:in `<module:ApplicationCable>'
chupa-text_1  | App 180 output:     /home/chupa-text/chupa-text-http-server/app/channels/application_cable/channel.rb:1:in `<main>'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `const_get'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `block (2 levels) in eager_load'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:733:in `block in ls'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `foreach'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `ls'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:404:in `block in eager_load'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `synchronize'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `eager_load'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `each'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `eager_load_all'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `instance_exec'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `run'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
chupa-text_1  | App 180 output:     /usr/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
chupa-text_1  | App 180 output:     /usr/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
chupa-text_1  | App 180 output:     /usr/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
chupa-text_1  | App 180 output:     /usr/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
chupa-text_1  | App 180 output:     /usr/lib/ruby/2.7.0/tsort.rb:347:in `each'
chupa-text_1  | App 180 output:     /usr/lib/ruby/2.7.0/tsort.rb:347:in `call'
chupa-text_1  | App 180 output:     /usr/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
chupa-text_1  | App 180 output:     /usr/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
chupa-text_1  | App 180 output:     /usr/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:60:in `run_initializers'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/application.rb:384:in `initialize!'
chupa-text_1  | App 180 output:     /home/chupa-text/chupa-text-http-server/config/environment.rb:5:in `<top (required)>'
chupa-text_1  | App 180 output:     config.ru:3:in `require_relative'
chupa-text_1  | App 180 output:     config.ru:3:in `block in <main>'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
chupa-text_1  | App 180 output:     config.ru:1:in `new'
chupa-text_1  | App 180 output:     config.ru:1:in `<main>'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:101:in `eval'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
chupa-text_1  | App 180 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:29:in `<main>'
chupa-text_1  | [ E 2021-04-11 14:53:36.3429 119/T17 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/chupa-text/chupa-text-http-server: The application encountered the following error: uninitialized constant ApplicationCable::ActionCable
chupa-text_1  | Did you mean?  Rational (NameError)
chupa-text_1  |   Error ID: 98dfa802
chupa-text_1  |   Error details saved to: /tmp/passenger-error-jcjbnc.html
chupa-text_1  |
chupa-text_1  | [ E 2021-04-11 14:53:36.3456 119/T8 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 98dfa802. Please see earlier logs for details about the error.
chupa-text_1  | [ N 2021-04-11 14:53:36.5768 119/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
chupa-text_1  | App 221 output: Error: The application encountered the following error: uninitialized constant ApplicationCable::ActionCable
chupa-text_1  | App 221 output: Did you mean?  Rational (NameError)
chupa-text_1  | App 221 output:     /home/chupa-text/chupa-text-http-server/app/channels/application_cable/channel.rb:2:in `<module:ApplicationCable>'
chupa-text_1  | App 221 output:     /home/chupa-text/chupa-text-http-server/app/channels/application_cable/channel.rb:1:in `<main>'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `const_get'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `block (2 levels) in eager_load'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:733:in `block in ls'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `foreach'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `ls'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:404:in `block in eager_load'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `synchronize'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `eager_load'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `each'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `eager_load_all'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `instance_exec'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `run'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
chupa-text_1  | App 221 output:     /usr/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
chupa-text_1  | App 221 output:     /usr/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
chupa-text_1  | App 221 output:     /usr/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
chupa-text_1  | App 221 output:     /usr/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
chupa-text_1  | App 221 output:     /usr/lib/ruby/2.7.0/tsort.rb:347:in `each'
chupa-text_1  | App 221 output:     /usr/lib/ruby/2.7.0/tsort.rb:347:in `call'
chupa-text_1  | App 221 output:     /usr/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
chupa-text_1  | App 221 output:     /usr/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
chupa-text_1  | App 221 output:     /usr/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:60:in `run_initializers'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/application.rb:384:in `initialize!'
chupa-text_1  | App 221 output:     /home/chupa-text/chupa-text-http-server/config/environment.rb:5:in `<top (required)>'
chupa-text_1  | App 221 output:     config.ru:3:in `require_relative'
chupa-text_1  | App 221 output:     config.ru:3:in `block in <main>'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
chupa-text_1  | App 221 output:     config.ru:1:in `new'
chupa-text_1  | App 221 output:     config.ru:1:in `<main>'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:101:in `eval'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
chupa-text_1  | App 221 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:29:in `<main>'
chupa-text_1  | [ E 2021-04-11 14:56:11.1691 119/T1c age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/chupa-text/chupa-text-http-server: The application encountered the following error: uninitialized constant ApplicationCable::ActionCable
chupa-text_1  | Did you mean?  Rational (NameError)
chupa-text_1  |   Error ID: c3cf9939
chupa-text_1  |   Error details saved to: /tmp/passenger-error-o9Uipa.html
chupa-text_1  |
chupa-text_1  | [ E 2021-04-11 14:56:11.1714 119/Ta age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is c3cf9939. Please see earlier logs for details about the error.
chupa-text_1  | App 260 output: Error: The application encountered the following error: uninitialized constant ApplicationCable::ActionCable
chupa-text_1  | App 260 output: Did you mean?  Rational (NameError)
chupa-text_1  | App 260 output:     /home/chupa-text/chupa-text-http-server/app/channels/application_cable/channel.rb:2:in `<module:ApplicationCable>'
chupa-text_1  | App 260 output:     /home/chupa-text/chupa-text-http-server/app/channels/application_cable/channel.rb:1:in `<main>'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `const_get'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `block (2 levels) in eager_load'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:733:in `block in ls'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `foreach'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `ls'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:404:in `block in eager_load'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `synchronize'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `eager_load'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `each'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `eager_load_all'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `instance_exec'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `run'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
chupa-text_1  | App 260 output:     /usr/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
chupa-text_1  | App 260 output:     /usr/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
chupa-text_1  | App 260 output:     /usr/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
chupa-text_1  | App 260 output:     /usr/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
chupa-text_1  | App 260 output:     /usr/lib/ruby/2.7.0/tsort.rb:347:in `each'
chupa-text_1  | App 260 output:     /usr/lib/ruby/2.7.0/tsort.rb:347:in `call'
chupa-text_1  | App 260 output:     /usr/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
chupa-text_1  | App 260 output:     /usr/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
chupa-text_1  | App 260 output:     /usr/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:60:in `run_initializers'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/railties-6.1.3.1/lib/rails/application.rb:384:in `initialize!'
chupa-text_1  | App 260 output:     /home/chupa-text/chupa-text-http-server/config/environment.rb:5:in `<top (required)>'
chupa-text_1  | App 260 output:     config.ru:3:in `require_relative'
chupa-text_1  | App 260 output:     config.ru:3:in `block in <main>'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
chupa-text_1  | App 260 output:     config.ru:1:in `new'
chupa-text_1  | App 260 output:     config.ru:1:in `<main>'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:101:in `eval'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
[log.zip](https://github.com/ranguba/chupa-text-docker/files/6292156/log.zip)

chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
chupa-text_1  | App 260 output:     /var/lib/gems/2.7.0/gems/passenger-6.0.8/src/helper-scripts/rack-preloader.rb:29:in `<main>'
chupa-text_1  | [ E 2021-04-11 14:56:19.3170 119/T1h age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/chupa-text/chupa-text-http-server: The application encountered the following error: uninitialized constant ApplicationCable::ActionCable
chupa-text_1  | Did you mean?  Rational (NameError)
chupa-text_1  |   Error ID: 59831ebc
chupa-text_1  |   Error details saved to: /tmp/passenger-error-qAmENc.html
chupa-text_1  |
chupa-text_1  | [ E 2021-04-11 14:56:19.3192 119/Tc age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 3-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 59831ebc. Please see earlier logs for details about the error.
```

**Comment by kou** [comment]
Thanks for your report.
I've fixed this.

**Comment by ioio000** [comment]
thanx, it working.
